### ISSUE TITLE
Create Button component

### ISSUE THREAD

**Issue by arthur404dev** [forjadev/mjo-forja-webpage#4]
Description:
Our waebapp have buttons and they have different styles. We need a button component that handle with all different styles.
Here are some examples:

![Image](https://user-images.githubusercontent.com/64755624/255735065-5339c309-746c-4928-9b11-9fd764f70001.png)
![Image](https://user-images.githubusercontent.com/64755624/255735066-a55dc95c-67ba-45d8-bbec-90f295e93596.png)

Figma: https://www.figma.com/file/PnSE4hrYIAkDgPPjVRxAUV/Landing-Page?type=design&node-id=356-341&mode=design&t=MmjRDGGDwGTDFmFB-0

Acceptance Criteria:
Should be able to see Button with all variants on Storybook.

**Comment by arthur404dev** [comment]
Girls, I think that we should have at least two variants, one default that looks like:

![Frame 1 (2)](https://github.com/forjadev/mjo-forja-webpage/assets/59490008/0b88a1f1-fe41-4418-ac88-653d3e834c85)

And our second variant should be something like:

![Button](https://github.com/forjadev/mjo-forja-webpage/assets/59490008/b66da752-6574-4fbe-b111-18f43c8623bd)

Do you think that we should have any prop to change the second variant color, or should we define that the color will always be that one?

**Comment by arthur404dev** [comment]
@junio12o Will we have different colors for the button border and background? If so, would you provide us some samples of the color variants we would have?

**Comment by JCastro456** [comment]
I believe we could implement a functionality that anticipates future color changes, making the code more robust and reducing the amount of work required.
Shall we add effects to the buttons? How is this done in companies? Can we add the effects while developing the button component? I believe this is discussed as well, isn't it?

**Comment by ghost** [comment]
@JCastro456 I liked your idea about using animation as an effect. 
My suggestion is in Landing Page Dark Mode: 
The first element “Vamos nessa” the button size could be larger with “padding”, “border-radius” and for text “font-size: `class=”p-{15px}, rounded-lg, text-sm” `.
About the color property could have as bg-primary-color: `background: linear-gradient(146deg, #3EF3FF 0%, #C8FBEE 100%);`  and as mode “:hover” could  apply the transparent. 
I believe that in Landing Page Light Mode can follow “dark mode” properties.

The point about our second element in both types of pages could keep the properties has already been suggested in the project model but adding “transform scale” in “:hover” mode.

This article shows basic information about “user’s attention with buttons”: https://arounda.agency/blog/7-button-design-basics-what-you-should-know

**Comment by JCastro456** [comment]
Good suggestions @kleck-lucena. Effects are always welcome to improve interaction with users.
We can also use hover:scale-110 and the button will have a 110% scaling animation when the mouse cursor is over it.

**Comment by kari-osk** [comment]
That's a great idea @kleck-lucena @JCastro456 about the effect! Maybe we should run it by the design team to see if they already have something in mind. 

And @arthur404dev, I agree with 2 variants:

primary:  "text + icon"

secondary:  "text"

**Comment by deniseschirmer** [comment]
I believe that with props we can change colors and change what we need in each part that the button is used.

**Comment by Gisellyrock** [comment]
Hi @arthur404dev!
Sounds good if we should have at least two variants, and I think that should be better if we use props, because it brings more dinamics for our component.

**Comment by junio256** [comment]
I've updated the [Landing Page layout](https://www.figma.com/file/PnSE4hrYIAkDgPPjVRxAUV/Landing-Page?type=design&node-id=22%3A30&mode=design&t=yex7gYa6IXVwmZLO-1) and now contains the version for light mode and defined all colors. This allow to pass the values to figma(#11) which I'll also do today

The buttons and major elements has been fixed to not make use of any broke value (i.e 15px)

**Comment by junio256** [comment]
About variations will have 2 named _**Callers**_ and _**Info**_, respectively.
The colors will be the same used on branding (in this case Dev (`#3ADBC8`) and Pro (`#FBB361`) primary colors)
![image](https://github.com/forjadev/mjo-forja-webpage/assets/53125029/e63614be-12be-49c5-8fc7-41be58a1d06e)
