### ISSUE TITLE
Create testimonial card component

### ISSUE THREAD

**Issue by MBrunoS** [forjadev/mjo-forja-webpage#6]
Description:
Our webapp has a card for the testimonials section, you can use lorem ipsun as place holder, like the example below:

![Image](https://user-images.githubusercontent.com/64755624/255736260-00a7f380-9c51-4d51-8433-085d2f7ccf04.png)
figma: https://www.figma.com/file/PnSE4hrYIAkDgPPjVRxAUV/Landing-Page?type=design&node-id=356-341&mode=design&t=MmjRDGGDwGTDFmFB-0

Acceptance Criteria:
Should be able to see the Testimonial card on Storybook

**Comment by MBrunoS** [comment]
I have already rebased this branch with the development, so you can refactor the classes to make use of the theme. And there's also the light/dark variations to consider.

**Comment by MBrunoS** [comment]
@jjribeiro1 I saw the refactoring, it's great. I believe that what's missing right now is only the storybook part, right?

**Comment by jjribeiro1** [comment]
@MBrunoS Yes. In figma it seems that there are no component variants so I believe everything is already done. Just missing the storybook part
