### ISSUE TITLE
Create media component

### ISSUE THREAD

**Issue by MBrunoS** [forjadev/mjo-forja-webpage#7]
Description:
Our webpage have a midia wrapper component that contains all Forja contacts (icon with link) like the example below.
Keep in mind that this component should display the icons with a light style and dark style, please check the 2 options on Figma, one on the main section and the other on the footer

Figma: https://www.figma.com/file/PnSE4hrYIAkDgPPjVRxAUV/Landing-Page?type=design&node-id=356-341&mode=design&t=MmjRDGGDwGTDFmFB-0

![Image](https://user-images.githubusercontent.com/64755624/255732199-142adf18-120f-4733-a2c8-d891dd73d1d7.png)

Acceptance Criteria:
Should be able to see media component on storybook

**Comment by limasid** [comment]
I submited social media component for analysis from PR

**Comment by MBrunoS** [comment]
@GreenProgramDev @SamuelPires1999 I have already rebased this branch with the development, so you can make use of the theme. Because there's the light/dark variations to consider.

**Comment by limasid** [comment]
Aded the links clickable for each icons
